apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 80                    # acesso pro service
    targetPort: 8080            # porta do pod que o service vai acessar
    nodePort: 30000
  type: NodePort
