apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017             # acesso pro service
    targetPort: 27017       # porta do pod que o service vai acessar 
  type: ClusterIP